# Sample State court data for expert annotation

# Import Libaries

In [1]:
import numpy as np
import pandas as pd

import json
import random

# Load the previously prepared data

In [2]:
df = pd.read_json("../experiments_701/state/data/state_citing_cited.json")
df.head()

,citing_cluster_id,citing_url,citing_court_id,citing_court_name,opinion_data,opinion_filenames,cited_cluster_id,cited_url,cited_court_id,cited_court_name,cited_case_name_short,cited_case_name,cited_case_name_full,cited_citations,cited_target
0,217242,https://www.courtlistener.com/opinion/217242/d...,ca1,Court of Appeals for the First Circuit,"[{'opinion_id': 217242, 'opinion_api': None, '...",[217242_010combined.txt],2526,https://www.courtlistener.com/opinion/2526/isl...,ca2,Court of Appeals for the Second Circuit,,"Island Park, LLC v. CSX Transportation","ISLAND PARK, LLC, Plaintiff-Appellee-Cross-App...","[2009 U.S. App. LEXIS 5219, 559 F.3d 96]",0
1,217242,https://www.courtlistener.com/opinion/217242/d...,ca1,Court of Appeals for the First Circuit,"[{'opinion_id': 217242, 'opinion_api': None, '...",[217242_010combined.txt],46231,https://www.courtlistener.com/opinion/46231/ur...,ca5,Court of Appeals for the Fifth Circuit,,Urban Developers LLC v. City of Jackson MS,"URBAN DEVELOPERS LLC, Plaintiff-Appellee, v. C...","[2006 WL 3012860, 2006 U.S. App. LEXIS 26435, ...",0
2,217242,https://www.courtlistener.com/opinion/217242/d...,ca1,Court of Appeals for the First Circuit,"[{'opinion_id': 217242, 'opinion_api': None, '...",[217242_010combined.txt],153651,https://www.courtlistener.com/opinion/153651/b...,ca10,Court of Appeals for the Tenth Circuit,Bateman,Bateman v. City of West Bountiful,"Wesley v. BATEMAN, Plaintiff-Appellant, v. CIT...","[1996 WL 384769, 1996 U.S. App. LEXIS 16429, 8...",0
3,217242,https://www.courtlistener.com/opinion/217242/d...,ca1,Court of Appeals for the First Circuit,"[{'opinion_id': 217242, 'opinion_api': None, '...",[217242_010combined.txt],179285,https://www.courtlistener.com/opinion/179285/c...,ca1,Court of Appeals for the First Circuit,Cortes-Rivera,Cortés-Rivera v. Department of Corrections & R...,"Enrique CORTÉS-RIVERA, Plaintiff, Appellant, v...","[2010 WL 4608750, 2010 U.S. App. LEXIS 23529, ...",0
4,217242,https://www.courtlistener.com/opinion/217242/d...,ca1,Court of Appeals for the First Circuit,"[{'opinion_id': 217242, 'opinion_api': None, '...",[217242_010combined.txt],199916,https://www.courtlistener.com/opinion/199916/d...,ca1,Court of Appeals for the First Circuit,Deniz-Marquez,Deniz v. Municipality of Guaynabo,"Calixto DENIZ, A/K/A Calixto Deniz Marquez, Pl...","[2002 WL 501056, 2002 U.S. App. LEXIS 6425, 28...",0

In [3]:
eda_cols = ['citing_cluster_id', 'citing_court_name', 'cited_cluster_id', 'cited_court_name', 'cited_target']

for col in eda_cols:
    print("----------")
    print(df[col].nunique())
    display(df[col].value_counts())

----------
1210

citing_cluster_id
4287446    1010
4289638     629
4295814     195
1467978     186
1808186     128
           ...
7345007       1
7035302       1
7007708       1
7220671       1
7035303       1
Name: count, Length: 1210, dtype: int64

----------
128

citing_court_name
Court of Appeals of Texas                                           4600
Louisiana Court of Appeal                                           3299
Appellate Division of the Supreme Court of the State of New York    1533
Court of Criminal Appeals of Texas                                  1013
Court of Criminal Appeals of Alabama                                 713
                                                                    ...
Hawaii Supreme Court                                                   3
Appellate Terms of the Supreme Court of New York                       3
Pennsylvania Court of Common Pleas, Dauphin County                     2
Pennsylvania Court of Common Pleas, Lycoming County                    2
Supreme Court of Vermont                                               1
Name: count, Length: 128, dtype: int64

----------
15603

cited_cluster_id
5682590    124
1729419    120
1719177     97
1782914     88
1772937     65
          ...
1858017      1
1875355      1
1938276      1
7670084      1
91972        1
Name: count, Length: 15603, dtype: int64

----------
229

cited_court_name
Texas Supreme Court                                            3258
Court of Appeals of Texas                                      2382
Louisiana Court of Appeal                                      2166
Supreme Court of the United States                             1421
Supreme Court of Louisiana                                     1309
                                                               ...
District Court, D. Utah                                           1
U.S. Circuit Court for the District of Eastern Pennsylvania       1
Arizona Tax Court                                                 1
U.S. Circuit Court for the District of Indiana                    1
United States Bankruptcy Court, E.D. New York                     1
Name: count, Length: 229, dtype: int64

----------
2

cited_target
0    21872
1     1210
Name: count, dtype: int64

# Identify the samples

In [4]:
keep = df[df["cited_target"] == 1]["cited_cluster_id"].to_list()
len(keep)

1210

In [17]:
random.seed(4)
keep_sampled = random.sample(keep, 7)
len(keep_sampled)

7

In [18]:
keep_sampled

[1772937, 1151894, 5337281, 1438803, 3622844, 2183335, 5051880]

In [19]:
citing_cluster_ids = df[df["cited_cluster_id"].isin(keep_sampled)]["citing_cluster_id"]
len(citing_cluster_ids)

159

In [20]:
sampled_df = df[df["citing_cluster_id"].isin(citing_cluster_ids)]
len(sampled_df)

2328

In [21]:
cited_cluster_ids = list(sampled_df["cited_cluster_id"].unique())
len(cited_cluster_ids)

1739

In [22]:
for col in eda_cols:
    print("----------")
    print(sampled_df[col].nunique())
    display(sampled_df[col].value_counts())

----------
159

citing_cluster_id
2369968     73
2330498     71
10612441    62
1212124     57
5802655     54
            ..
1154372      2
7771877      1
4988230      1
7626344      1
7616342      1
Name: count, Length: 159, dtype: int64

----------
21

citing_court_name
Louisiana Court of Appeal                                           1094
New York Surrogate's Court                                           255
Supreme Judicial Court of Maine                                      194
Michigan Court of Appeals                                            143
California Court of Appeal                                           111
District Court of Appeal of Florida                                  105
Tennessee Supreme Court                                               73
Court of Appeals for the Tenth Circuit                                48
Supreme Court of Colorado                                             45
Superior Court of Maine                                               38
Appellate Division of the Supreme Court of the State of New York      33
Wisconsin Supreme Court                                               33
Court of Appeals of Maryland                                          32
Idaho Supreme Court                                                   27
Supreme Court of Kansas                                               24
Supreme Court of Georgia                                              19
Court of Appeals of Virginia                                          16
Washington Supreme Court                                              15
District Court, M.D. Florida                                          12
Mississippi Supreme Court                                              8
Supreme Court of Louisiana                                             3
Name: count, dtype: int64

----------
1739

cited_cluster_id
1772937    65
3622844    27
5051880    24
1438803    16
3646175    11
           ..
5021830     1
5007480     1
5005757     1
4997036     1
7532615     1
Name: count, Length: 1739, dtype: int64

----------
111

cited_court_name
Louisiana Court of Appeal                752
Supreme Court of Louisiana               309
Supreme Judicial Court of Maine          144
New York Surrogate's Court               140
New York Court of Appeals                134
                                        ...
Ohio Supreme Court                         1
Wyoming Supreme Court                      1
District of Columbia Court of Appeals      1
Kentucky Supreme Court                     1
South Dakota Supreme Court                 1
Name: count, Length: 111, dtype: int64

----------
2

cited_target
0    2169
1     159
Name: count, dtype: int64

# Save the txt files for processing against CLReplica

In [23]:
#with open('data/state/citing_ids.txt', 'w') as f:
#    for number in citing_cluster_ids:
#        f.write(f"{number}\n")

In [24]:
#with open('data/state/cited_ids.txt', 'w') as f:
#    for number in cited_cluster_ids:
#        f.write(f"{number}\n")

# Load the citing data extracted from CLReplica

In [25]:
with open('data/state/citing_opinions.json', 'r') as f:
    results = json.load(f)

In [26]:
citing_metadata = pd.DataFrame.from_dict(results, orient='index')
citing_metadata = citing_metadata.reset_index().rename(columns={'index': 'citing_cluster_id'})
citing_metadata.head()

,citing_cluster_id,citing_url,citing_court_id,citing_court_name,opinion_data,cited_cluster_ids
0,1198927,https://www.courtlistener.com/opinion/1198927/...,colo,Supreme Court of Colorado,"[{'opinion_id': 1198927, 'opinion_api': None, ...","[378896, 450379, 474635, 514595, 600365, 65464..."
1,1368933,https://www.courtlistener.com/opinion/1368933/...,ga,Supreme Court of Georgia,"[{'opinion_id': 1368933, 'opinion_api': None, ...","[1270745, 1278234, 1351131, 1417408, 3405049, ..."
2,1438803,https://www.courtlistener.com/opinion/1438803/...,me,Supreme Judicial Court of Maine,"[{'opinion_id': 9630244, 'opinion_api': None, ...","[532093, 540919, 554938, 5129592, 110959, 1112..."
3,1477013,https://www.courtlistener.com/opinion/1477013/...,ca10,Court of Appeals for the Tenth Circuit,"[{'opinion_id': 1477013, 'opinion_api': None, ...","[88802, 99404, 1482490, 1549672, 1566128, 3571..."
4,1477224,https://www.courtlistener.com/opinion/1477224/...,me,Supreme Judicial Court of Maine,"[{'opinion_id': 1477224, 'opinion_api': None, ...","[1493880, 2054479, 5142881, 109925, 111262, 14..."

In [27]:
citing_metadata.columns

Index(['citing_cluster_id', 'citing_url', 'citing_court_id',
       'citing_court_name', 'opinion_data', 'cited_cluster_ids'],
      dtype='object')

In [28]:
citing_metadata = citing_metadata[['citing_cluster_id', 'citing_url', 'citing_court_name', 'cited_cluster_ids']]
citing_exploded = citing_metadata.explode("cited_cluster_ids", ignore_index=True)

citing_exploded.rename(columns={"cited_cluster_ids": "cited_cluster_id"}, inplace=True)
citing_exploded["cited_cluster_id"] = citing_exploded["cited_cluster_id"].astype(int)
citing_exploded.head()

,citing_cluster_id,citing_url,citing_court_name,cited_cluster_id
0,1198927,https://www.courtlistener.com/opinion/1198927/...,Supreme Court of Colorado,378896
1,1198927,https://www.courtlistener.com/opinion/1198927/...,Supreme Court of Colorado,450379
2,1198927,https://www.courtlistener.com/opinion/1198927/...,Supreme Court of Colorado,474635
3,1198927,https://www.courtlistener.com/opinion/1198927/...,Supreme Court of Colorado,514595
4,1198927,https://www.courtlistener.com/opinion/1198927/...,Supreme Court of Colorado,600365

# Load the cited data extracted from CLReplica

In [50]:
with open('data/state/cited_opinions.json', 'r') as f:
    results = json.load(f)

In [51]:
cited_metadata = pd.DataFrame.from_dict(results, orient='index')
cited_metadata = cited_metadata.reset_index().rename(columns={'index': 'cited_cluster_id'})
cited_metadata.head()

,cited_cluster_id,cited_url,cited_court_id,cited_court_name,cited_case_name_short,cited_case_name,cited_case_name_full,cited_citations
0,1094336,https://www.courtlistener.com/opinion/1094336/...,lactapp,Louisiana Court of Appeal,Poche,"State Block, Inc. v. Poche",,"[1984 La. App. LEXIS 7866, 15 Educ. L. Rep. 13..."
1,1094340,https://www.courtlistener.com/opinion/1094340/...,lactapp,Louisiana Court of Appeal,Stokes,Palmer v. Stokes,,[444 So. 2d 213]
2,1094664,https://www.courtlistener.com/opinion/1094664/...,la,Supreme Court of Louisiana,Mistich,"Mistich v. Volkswagen of Germany, Inc.",,"[1996 WL 37969, 666 So. 2d 1073]"
3,1099721,https://www.courtlistener.com/opinion/1099721/...,lactapp,Louisiana Court of Appeal,Reeves,Reeves v. Reeves,,"[2002 WL 1677744, 823 So. 2d 1023]"
4,1100354,https://www.courtlistener.com/opinion/1100354/...,lactapp,Louisiana Court of Appeal,CCHC,Union Planters Bank v. CCHC,,[907 So. 2d 129]

In [52]:
cited_metadata.columns

Index(['cited_cluster_id', 'cited_url', 'cited_court_id', 'cited_court_name',
       'cited_case_name_short', 'cited_case_name', 'cited_case_name_full',
       'cited_citations'],
      dtype='object')

In [53]:
cited_metadata = cited_metadata[['cited_cluster_id', 'cited_url', 'cited_court_name', 'cited_case_name_short', 'cited_case_name', 'cited_citations']]
cited_metadata["cited_cluster_id"] = cited_metadata["cited_cluster_id"].astype(int)
cited_metadata.head()

,cited_cluster_id,cited_url,cited_court_name,cited_case_name_short,cited_case_name,cited_citations
0,1094336,https://www.courtlistener.com/opinion/1094336/...,Louisiana Court of Appeal,Poche,"State Block, Inc. v. Poche","[1984 La. App. LEXIS 7866, 15 Educ. L. Rep. 13..."
1,1094340,https://www.courtlistener.com/opinion/1094340/...,Louisiana Court of Appeal,Stokes,Palmer v. Stokes,[444 So. 2d 213]
2,1094664,https://www.courtlistener.com/opinion/1094664/...,Supreme Court of Louisiana,Mistich,"Mistich v. Volkswagen of Germany, Inc.","[1996 WL 37969, 666 So. 2d 1073]"
3,1099721,https://www.courtlistener.com/opinion/1099721/...,Louisiana Court of Appeal,Reeves,Reeves v. Reeves,"[2002 WL 1677744, 823 So. 2d 1023]"
4,1100354,https://www.courtlistener.com/opinion/1100354/...,Louisiana Court of Appeal,CCHC,Union Planters Bank v. CCHC,[907 So. 2d 129]

# Create the output df

In [54]:
output = pd.merge(citing_exploded, cited_metadata, how="left", on="cited_cluster_id")
output.head()

,citing_cluster_id,citing_url,citing_court_name,cited_cluster_id,cited_url,cited_court_name,cited_case_name_short,cited_case_name,cited_citations
0,1198927,https://www.courtlistener.com/opinion/1198927/...,Supreme Court of Colorado,378896,https://www.courtlistener.com/opinion/378896/u...,Court of Appeals for the Fifth Circuit,,United States v. Jo Ann Williams,"[1980 U.S. App. LEXIS 15233, 622 F.2d 830]"
1,1198927,https://www.courtlistener.com/opinion/1198927/...,Supreme Court of Colorado,450379,https://www.courtlistener.com/opinion/450379/u...,Court of Appeals for the Second Circuit,,United States v. Barbara Fama,"[1985 U.S. App. LEXIS 30301, 758 F.2d 834]"
2,1198927,https://www.courtlistener.com/opinion/1198927/...,Supreme Court of Colorado,474635,https://www.courtlistener.com/opinion/474635/u...,Court of Appeals for the Tenth Circuit,,United States v. Arvle Edgar Medlin,"[1986 U.S. App. LEXIS 27949, 798 F.2d 407]"
3,1198927,https://www.courtlistener.com/opinion/1198927/...,Supreme Court of Colorado,514595,https://www.courtlistener.com/opinion/514595/u...,Court of Appeals for the Fifth Circuit,,United States v. Bruce L. Craig,"[1988 WL 125029, 1988 U.S. App. LEXIS 16982, 8..."
4,1198927,https://www.courtlistener.com/opinion/1198927/...,Supreme Court of Colorado,600365,https://www.courtlistener.com/opinion/600365/u...,Court of Appeals for the Fifth Circuit,,"United States v. Felmon Lakeith Laury, A/K/A F...","[1993 WL 52543, 1993 U.S. App. LEXIS 3437, 985..."

In [55]:
len(output)

2376

In [56]:
for col in eda_cols[:-1]:
    print("----------")
    print(output[col].nunique())
    display(output[col].value_counts())

----------
159

citing_cluster_id
2369968     73
2330498     71
10612441    62
1212124     57
5802655     55
            ..
1154372      2
7616342      1
7626344      1
7771877      1
4988230      1
Name: count, Length: 159, dtype: int64

----------
21

citing_court_name
Louisiana Court of Appeal                                           1132
New York Surrogate's Court                                           259
Supreme Judicial Court of Maine                                      194
Michigan Court of Appeals                                            143
California Court of Appeal                                           112
District Court of Appeal of Florida                                  107
Tennessee Supreme Court                                               73
Court of Appeals for the Tenth Circuit                                48
Supreme Court of Colorado                                             45
Superior Court of Maine                                               38
Appellate Division of the Supreme Court of the State of New York      36
Wisconsin Supreme Court                                               33
Court of Appeals of Maryland                                          32
Idaho Supreme Court                                                   27
Supreme Court of Kansas                                               24
Supreme Court of Georgia                                              19
Court of Appeals of Virginia                                          16
Washington Supreme Court                                              15
District Court, M.D. Florida                                          12
Mississippi Supreme Court                                              8
Supreme Court of Louisiana                                             3
Name: count, dtype: int64

----------
1774

cited_cluster_id
1772937    65
3622844    27
5051880    24
1438803    16
3646175    11
           ..
1107136     1
1102098     1
1094075     1
2551561     1
4388623     1
Name: count, Length: 1774, dtype: int64

----------
111

cited_court_name
Louisiana Court of Appeal                764
Supreme Court of Louisiana               335
Supreme Judicial Court of Maine          144
New York Surrogate's Court               141
New York Court of Appeals                135
                                        ...
Court of Appeals of Tennessee              1
Ohio Supreme Court                         1
Wyoming Supreme Court                      1
District of Columbia Court of Appeals      1
South Dakota Supreme Court                 1
Name: count, Length: 111, dtype: int64

# Save the output df

In [58]:
output.to_csv("data/state/state_citing_cited.csv", index=False)

# Save each citing cluster as a separate csv for expert annotation

In [59]:
for citing_cluster_id in output["citing_cluster_id"].unique():
    annotate = output[output["citing_cluster_id"] == citing_cluster_id].copy()
    annotate["expert"] = None
    annotate["expert_label"] = None
    annotate["expert_notes"] = None
    num_cited = annotate["cited_cluster_id"].nunique()

    expert_folder = f"data/state/annotations/"
    
    annotate.to_csv(f"{expert_folder}/{num_cited}_{citing_cluster_id}.csv", index=False)