# Sample Bankruptcy court data for expert annotation

# Import Libaries

In [1]:
import numpy as np
import pandas as pd

import json
import random

# Load the previously prepared data

In [2]:
df = pd.read_json("../experiments_701/bankruptcy/data/bankruptcy_citing_cited.json")
df.head()

,citing_cluster_id,citing_url,citing_court_id,citing_court_name,opinion_data,opinion_filenames,cited_cluster_id,cited_url,cited_court_id,cited_court_name,cited_case_name_short,cited_case_name,cited_case_name_full,cited_citations,cited_target
0,73856,https://www.courtlistener.com/opinion/73856/mo...,ca11,Court of Appeals for the Eleventh Circuit,"[{'opinion_id': 73856, 'opinion_api': None, 'o...",[73856_010combined.txt],515532,https://www.courtlistener.com/opinion/515532/i...,ca11,Court of Appeals for the Eleventh Circuit,,In the Matter of Paul D. Folendore and Helen H...,In the Matter of Paul D. FOLENDORE and Helen H...,"[1989 WL 28, 18 Bankr. Ct. Dec. (CRR) 1247, 19...",0
1,73856,https://www.courtlistener.com/opinion/73856/mo...,ca11,Court of Appeals for the Eleventh Circuit,"[{'opinion_id': 73856, 'opinion_api': None, 'o...",[73856_010combined.txt],583488,https://www.courtlistener.com/opinion/583488/i...,ca11,Court of Appeals for the Eleventh Circuit,,,"In the Matter of Saybrook Manufacturing Co., I...","[23 Bankr. Ct. Dec. (CRR) 355, 1992 U.S. App. ...",0
2,73856,https://www.courtlistener.com/opinion/73856/mo...,ca11,Court of Appeals for the Eleventh Circuit,"[{'opinion_id': 73856, 'opinion_api': None, 'o...",[73856_010combined.txt],583996,https://www.courtlistener.com/opinion/583996/i...,ca7,Court of Appeals for the Seventh Circuit,,"In Re Henry E. Montoya, M.D. And Juanita F. Mo...","In Re Henry E. MONTOYA, M.D. and Juanita F. Mo...","[1992 WL 141941, 1992 U.S. App. LEXIS 14502, 7...",0
3,73856,https://www.courtlistener.com/opinion/73856/mo...,ca11,Court of Appeals for the Eleventh Circuit,"[{'opinion_id': 73856, 'opinion_api': None, 'o...",[73856_010combined.txt],607973,https://www.courtlistener.com/opinion/607973/i...,ca10,Court of Appeals for the Tenth Circuit,,"In Re William E. Richards, Debtor, United Stat...","In Re William E. RICHARDS, Debtor, UNITED STAT...","[1993 WL 182728, 1993 U.S. App. LEXIS 12648, 7...",0
4,73856,https://www.courtlistener.com/opinion/73856/mo...,ca11,Court of Appeals for the Eleventh Circuit,"[{'opinion_id': 73856, 'opinion_api': None, 'o...",[73856_010combined.txt],627502,https://www.courtlistener.com/opinion/627502/i...,ca11,Court of Appeals for the Eleventh Circuit,,"In Re Empire for Him, Inc., Debtor. Capital Fa...","In Re EMPIRE FOR HIM, INC., Debtor. CAPITAL FA...","[1993 WL 325352, 24 Bankr. Ct. Dec. (CRR) 1103...",0

In [3]:
eda_cols = ['citing_cluster_id', 'citing_court_name', 'cited_cluster_id', 'cited_court_name', 'cited_target']

for col in eda_cols:
    print("----------")
    print(df[col].nunique())
    display(df[col].value_counts())

----------
1493

citing_cluster_id
8337992    292
1549737    261
1962505    260
2196109    247
1933158    199
          ...
1872340      1
8518697      1
1865723      1
1535105      1
1936149      1
Name: count, Length: 1493, dtype: int64

----------
207

citing_court_name
United States Bankruptcy Court, E.D. Pennsylvania                 2501
United States Bankruptcy Court, N.D. Illinois                     1510
United States Bankruptcy Appellate Panel for the Ninth Circuit    1300
United States Bankruptcy Court, S.D. New York                     1297
United States Bankruptcy Court, N.D. Indiana                      1198
                                                                  ...
District Court, W.D. Washington                                      8
Vermont Superior Court                                               8
District Court, W.D. North Carolina                                  7
District Court, S.D. Indiana                                         6
United States Bankruptcy Court, S.D. West Virginia                   2
Name: count, Length: 207, dtype: int64

----------
21257

cited_cluster_id
112522     146
1887361    122
1538334    101
110017      77
111722      76
          ...
1810829      1
1826882      1
1829805      1
1847539      1
1457542      1
Name: count, Length: 21257, dtype: int64

----------
335

cited_court_name
Supreme Court of the United States                   4193
Court of Appeals for the Ninth Circuit               1510
Court of Appeals for the Seventh Circuit             1269
United States Bankruptcy Court, E.D. Pennsylvania    1265
Court of Appeals for the Fifth Circuit               1224
                                                     ...
New York County Courts                                  1
Connecticut Superior Court                              1
Court of Common Pleas of Ohio, Hamilton County          1
Jackson County Court of Common Pleas                    1
City of Cleveland Municipal Court                       1
Name: count, Length: 335, dtype: int64

----------
2

cited_target
0    36427
1     1515
Name: count, dtype: int64

# Identify the samples

In [4]:
keep = df[df["cited_target"] == 1]["cited_cluster_id"].to_list()
len(keep)

1515

In [5]:
random.seed(7)
keep_sampled = random.sample(keep, 2)
len(keep_sampled)

2

In [6]:
keep_sampled

[1976820, 1887361]

In [7]:
citing_cluster_ids = df[df["cited_cluster_id"].isin(keep_sampled)]["citing_cluster_id"]
len(citing_cluster_ids)

124

In [8]:
sampled_df = df[df["citing_cluster_id"].isin(citing_cluster_ids)]
len(sampled_df)

2129

In [9]:
cited_cluster_ids = list(sampled_df["cited_cluster_id"].unique())
len(cited_cluster_ids)

879

In [10]:
for col in eda_cols:
    print("----------")
    print(sampled_df[col].nunique())
    display(sampled_df[col].value_counts())

----------
124

citing_cluster_id
1902118    76
8527657    69
1523787    62
1865101    62
1547353    58
           ..
1548877     2
1538635     1
1872340     1
1535105     1
1970688     1
Name: count, Length: 124, dtype: int64

----------
61

citing_court_name
United States Bankruptcy Court, D. Kansas             161
United States Bankruptcy Court, S.D. New York         156
United States Bankruptcy Court, N.D. Georgia          117
United States Bankruptcy Court, S.D. Ohio             106
United States Bankruptcy Court, D. Utah                96
                                                     ...
District Court, E.D. California                         5
United States Bankruptcy Court, M.D. Georgia            4
United States Bankruptcy Court, D. Oregon               3
United States Bankruptcy Court, S.D. West Virginia      2
Bankruptcy Appellate Panel of the First Circuit         1
Name: count, Length: 61, dtype: int64

----------
879

cited_cluster_id
1887361    122
1887706     39
1887144     32
1970505     31
1970642     26
          ...
1937738      1
1969702      1
1969730      1
1997290      1
779410       1
Name: count, Length: 879, dtype: int64

----------
164

cited_court_name
United States Bankruptcy Court, D. Utah            133
Supreme Court of the United States                 119
United States Bankruptcy Court, S.D. California    117
United States Bankruptcy Court, D. Colorado         92
United States Bankruptcy Court, S.D. Ohio           69
                                                  ...
Nebraska Supreme Court                               1
California Supreme Court                             1
Connecticut Appellate Court                          1
District Court, W.D. Missouri                        1
South Dakota Supreme Court                           1
Name: count, Length: 164, dtype: int64

----------
2

cited_target
0    2005
1     124
Name: count, dtype: int64

# Save the txt files for processing against CLReplica

In [11]:
#with open('data/bankruptcy/citing_ids.txt', 'w') as f:
#    for number in citing_cluster_ids:
#        f.write(f"{number}\n")

In [12]:
#with open('data/bankruptcy/cited_ids.txt', 'w') as f:
#    for number in cited_cluster_ids:
#        f.write(f"{number}\n")

# Load the citing data extracted from CLReplica

In [13]:
with open('data/bankruptcy/citing_opinions.json', 'r') as f:
    results = json.load(f)

In [14]:
citing_metadata = pd.DataFrame.from_dict(results, orient='index')
citing_metadata = citing_metadata.reset_index().rename(columns={'index': 'citing_cluster_id'})
citing_metadata.head()

,citing_cluster_id,citing_url,citing_court_id,citing_court_name,opinion_data,cited_cluster_ids
0,382157,https://www.courtlistener.com/opinion/382157/i...,ca8,Court of Appeals for the Eighth Circuit,"[{'opinion_id': 382157, 'opinion_api': None, '...","[1887144, 1887361, 1887416, 1887706, 1970474, ..."
1,411769,https://www.courtlistener.com/opinion/411769/i...,ca8,Court of Appeals for the Eighth Circuit,"[{'opinion_id': 411769, 'opinion_api': None, '...","[382157, 402517, 410944, 1537909, 1538046, 153..."
2,420012,https://www.courtlistener.com/opinion/420012/g...,ca10,Court of Appeals for the Tenth Circuit,"[{'opinion_id': 420012, 'opinion_api': None, '...","[398967, 402517, 409199, 410944, 411769, 41557..."
3,475775,https://www.courtlistener.com/opinion/475775/i...,ca6,Court of Appeals for the Sixth Circuit,"[{'opinion_id': 475775, 'opinion_api': None, '...","[100898, 103240, 103393, 1486562, 1500608, 150..."
4,1523787,https://www.courtlistener.com/opinion/1523787/...,tnmb,"United States Bankruptcy Court, M.D. Tennessee","[{'opinion_id': 1523787, 'opinion_api': None, ...","[101939, 111984, 197912, 432325, 719750, 10609..."

In [15]:
citing_metadata.columns

Index(['citing_cluster_id', 'citing_url', 'citing_court_id',
       'citing_court_name', 'opinion_data', 'cited_cluster_ids'],
      dtype='object')

In [16]:
citing_metadata = citing_metadata[['citing_cluster_id', 'citing_url', 'citing_court_name', 'cited_cluster_ids']]
citing_exploded = citing_metadata.explode("cited_cluster_ids", ignore_index=True)

citing_exploded.rename(columns={"cited_cluster_ids": "cited_cluster_id"}, inplace=True)
citing_exploded["cited_cluster_id"] = citing_exploded["cited_cluster_id"].astype(int)
citing_exploded.head()

,citing_cluster_id,citing_url,citing_court_name,cited_cluster_id
0,382157,https://www.courtlistener.com/opinion/382157/i...,Court of Appeals for the Eighth Circuit,1887144
1,382157,https://www.courtlistener.com/opinion/382157/i...,Court of Appeals for the Eighth Circuit,1887361
2,382157,https://www.courtlistener.com/opinion/382157/i...,Court of Appeals for the Eighth Circuit,1887416
3,382157,https://www.courtlistener.com/opinion/382157/i...,Court of Appeals for the Eighth Circuit,1887706
4,382157,https://www.courtlistener.com/opinion/382157/i...,Court of Appeals for the Eighth Circuit,1970474

# Load the cited data extracted from CLReplica

In [17]:
with open('data/bankruptcy/cited_opinions.json', 'r') as f:
    results = json.load(f)

In [18]:
cited_metadata = pd.DataFrame.from_dict(results, orient='index')
cited_metadata = cited_metadata.reset_index().rename(columns={'index': 'cited_cluster_id'})
cited_metadata.head()

,cited_cluster_id,cited_url,cited_court_id,cited_court_name,cited_case_name_short,cited_case_name,cited_case_name_full,cited_citations
0,100898,https://www.courtlistener.com/opinion/100898/k...,scotus,Supreme Court of the United States,,Kansas City Terminal Railway Co. v. Central Un...,KANSAS CITY TERMINAL RAILWAY COMPANY Et Al. v....,"[1926 U.S. LEXIS 634, 70 L. Ed. 1028, 46 S. Ct..."
1,101939,https://www.courtlistener.com/opinion/101939/a...,scotus,Supreme Court of the United States,,"Atlantic Cleaners & Dyers, Inc. v. United States","ATLANTIC CLEANERS & DYERS, INC., Et Al. v. UNI...","[1932 U.S. LEXIS 612, 76 L. Ed. 1204, 52 S. Ct..."
2,103240,https://www.courtlistener.com/opinion/103240/c...,scotus,Supreme Court of the United States,Case,Case v. Los Angeles Lumber Products Co.,CASE Et Al. v. LOS ANGELES LUMBER PRODUCTS CO....,"[1939 U.S. LEXIS 1039, 84 L. Ed. 110, 60 S. Ct..."
3,103393,https://www.courtlistener.com/opinion/103393/a...,scotus,Supreme Court of the United States,,American United Mutual Life Insurance v. City ...,American United Mutual Life Insurance Co. v. C...,"[1940 U.S. LEXIS 1105, 85 L. Ed. 91, 61 S. Ct...."
4,111984,https://www.courtlistener.com/opinion/111984/u...,scotus,Supreme Court of the United States,,United Sav. Assn. of Tex. v. Timbers of Inwood...,United Savings Association of Texas v. Timbers...,"[16 Bankr. Ct. Dec. (CRR) 1369, 17 Collier Ban..."

In [19]:
cited_metadata.columns

Index(['cited_cluster_id', 'cited_url', 'cited_court_id', 'cited_court_name',
       'cited_case_name_short', 'cited_case_name', 'cited_case_name_full',
       'cited_citations'],
      dtype='object')

In [20]:
cited_metadata = cited_metadata[['cited_cluster_id', 'cited_url', 'cited_court_name', 'cited_case_name_short', 'cited_case_name', 'cited_citations']]
cited_metadata["cited_cluster_id"] = cited_metadata["cited_cluster_id"].astype(int)
cited_metadata.head()

,cited_cluster_id,cited_url,cited_court_name,cited_case_name_short,cited_case_name,cited_citations
0,100898,https://www.courtlistener.com/opinion/100898/k...,Supreme Court of the United States,,Kansas City Terminal Railway Co. v. Central Un...,"[1926 U.S. LEXIS 634, 70 L. Ed. 1028, 46 S. Ct..."
1,101939,https://www.courtlistener.com/opinion/101939/a...,Supreme Court of the United States,,"Atlantic Cleaners & Dyers, Inc. v. United States","[1932 U.S. LEXIS 612, 76 L. Ed. 1204, 52 S. Ct..."
2,103240,https://www.courtlistener.com/opinion/103240/c...,Supreme Court of the United States,Case,Case v. Los Angeles Lumber Products Co.,"[1939 U.S. LEXIS 1039, 84 L. Ed. 110, 60 S. Ct..."
3,103393,https://www.courtlistener.com/opinion/103393/a...,Supreme Court of the United States,,American United Mutual Life Insurance v. City ...,"[1940 U.S. LEXIS 1105, 85 L. Ed. 91, 61 S. Ct...."
4,111984,https://www.courtlistener.com/opinion/111984/u...,Supreme Court of the United States,,United Sav. Assn. of Tex. v. Timbers of Inwood...,"[16 Bankr. Ct. Dec. (CRR) 1369, 17 Collier Ban..."

# Create the output df

In [21]:
output = pd.merge(citing_exploded, cited_metadata, how="left", on="cited_cluster_id")
output.head()

,citing_cluster_id,citing_url,citing_court_name,cited_cluster_id,cited_url,cited_court_name,cited_case_name_short,cited_case_name,cited_citations
0,382157,https://www.courtlistener.com/opinion/382157/i...,Court of Appeals for the Eighth Circuit,1887144,https://www.courtlistener.com/opinion/1887144/...,"United States Bankruptcy Court, N.D. California",In Re Burrell,In Re Burrell,"[5 Bankr. Ct. Dec. (CRR) 1321, 1980 Bankr. LEX..."
1,382157,https://www.courtlistener.com/opinion/382157/i...,Court of Appeals for the Eighth Circuit,1887361,https://www.courtlistener.com/opinion/1887361/...,"United States Bankruptcy Court, D. Utah",In Re Iacovoni,In Re Iacovoni,[2 B.R. 256]
2,382157,https://www.courtlistener.com/opinion/382157/i...,Court of Appeals for the Eighth Circuit,1887416,https://www.courtlistener.com/opinion/1887416/...,"United States Bankruptcy Court, W.D. Missouri",In re Curtis,Matter of Curtis,"[5 Bankr. Ct. Dec. (CRR) 1214, 1979 Bankr. LEX..."
3,382157,https://www.courtlistener.com/opinion/382157/i...,Court of Appeals for the Eighth Circuit,1887706,https://www.courtlistener.com/opinion/1887706/...,"United States Bankruptcy Court, S.D. California",In Re Beaver,In Re Beaver,"[5 Bankr. Ct. Dec. (CRR) 1285, 1980 Bankr. LEX..."
4,382157,https://www.courtlistener.com/opinion/382157/i...,Court of Appeals for the Eighth Circuit,1970474,https://www.courtlistener.com/opinion/1970474/...,"United States Bankruptcy Court, C.D. California",In Re Bloom,In Re Bloom,"[6 Bankr. Ct. Dec. (CRR) 141, 1980 Bankr. LEXI..."

In [22]:
len(output)

2126

In [23]:
for col in eda_cols[:-1]:
    print("----------")
    print(output[col].nunique())
    display(output[col].value_counts())

----------
124

citing_cluster_id
1902118    76
8527657    69
1523787    62
1865101    62
1547353    58
           ..
1548877     2
1538635     1
1970688     1
1872340     1
1535105     1
Name: count, Length: 124, dtype: int64

----------
61

citing_court_name
United States Bankruptcy Court, D. Kansas             161
United States Bankruptcy Court, S.D. New York         156
United States Bankruptcy Court, N.D. Georgia          116
United States Bankruptcy Court, S.D. Ohio             106
United States Bankruptcy Court, D. Utah                96
                                                     ...
District Court, D. South Dakota                         5
United States Bankruptcy Court, M.D. Georgia            4
United States Bankruptcy Court, D. Oregon               3
United States Bankruptcy Court, S.D. West Virginia      2
Bankruptcy Appellate Panel of the First Circuit         1
Name: count, Length: 61, dtype: int64

----------
879

cited_cluster_id
1887361    122
1887706     39
1887144     32
1970505     31
1970642     26
          ...
1548485      1
1864042      1
1864113      1
1992380      1
779410       1
Name: count, Length: 879, dtype: int64

----------
164

cited_court_name
United States Bankruptcy Court, D. Utah            133
United States Bankruptcy Court, S.D. California    117
Supreme Court of the United States                 117
United States Bankruptcy Court, D. Colorado         92
United States Bankruptcy Court, S.D. Ohio           69
                                                  ...
California Court of Appeal                           1
United States Bankruptcy Court, D. Hawaii            1
District Court, D. Maryland                          1
District Court, M.D. Georgia                         1
Court of Appeals of North Carolina                   1
Name: count, Length: 164, dtype: int64

# Save the output df

In [24]:
output.to_csv("data/bankruptcy/bankruptcy_citing_cited.csv", index=False)

# Save each citing cluster as a separate csv for expert annotation

In [25]:
for citing_cluster_id in output["citing_cluster_id"].unique():
    annotate = output[output["citing_cluster_id"] == citing_cluster_id].copy()
    annotate["expert"] = None
    annotate["expert_label"] = None
    annotate["expert_notes"] = None
    num_cited = annotate["cited_cluster_id"].nunique()

    expert_folder = f"data/bankruptcy/annotations/"
    
    annotate.to_csv(f"{expert_folder}/{num_cited}_{citing_cluster_id}.csv", index=False)