# Sample Federal Lower Court data for expert annotation

# Import Libraries

In [1]:
import numpy as np
import pandas as pd

import json
import random

# Load the previously prepared data

In [2]:
df = pd.read_json("../experiments_701/fed/data/fed_citing_cited.json")
df.head()

,citing_cluster_id,citing_url,citing_court_id,citing_court_name,opinion_data,opinion_filenames,cited_cluster_id,cited_url,cited_court_id,cited_court_name,cited_case_name_short,cited_case_name,cited_case_name_full,cited_citations,cited_target
0,237668,https://www.courtlistener.com/opinion/237668/t...,ca6,Court of Appeals for the Sixth Circuit,"[{'opinion_id': 237668, 'opinion_api': None, '...",[237668_010combined.txt],1569044,https://www.courtlistener.com/opinion/1569044/...,ohsd,"District Court, S.D. Ohio",Shafer,London Guarantee & Accident Co. v. Shafer,"LONDON GUARANTEE & ACCIDENT CO., Limited, v. S...","[1940 U.S. Dist. LEXIS 2322, 35 F. Supp. 647]",0
1,237668,https://www.courtlistener.com/opinion/237668/t...,ca6,Court of Appeals for the Sixth Circuit,"[{'opinion_id': 237668, 'opinion_api': None, '...",[237668_010combined.txt],4025274,https://www.courtlistener.com/opinion/4025274/...,ohio,Ohio Supreme Court,,Bloom-Rosenblum-Kline Co. v. Union Indemnity Co.,The Bloom-Rosenblum-Kline Co. v. Union Indemni...,"[1929 Ohio LEXIS 287, 7 Ohio Law. Abs. 379, 12...",0
2,237668,https://www.courtlistener.com/opinion/237668/t...,ca6,Court of Appeals for the Sixth Circuit,"[{'opinion_id': 237668, 'opinion_api': None, '...",[237668_010combined.txt],4025744,https://www.courtlistener.com/opinion/4025744/...,ohio,Ohio Supreme Court,Leonard,Leonard v. Murdock,"Leonard, Appellee, v. Murdock Et Al.; The Ocea...","[1946 Ohio LEXIS 268, 33 Ohio Op. 269, 147 Ohi...",0
3,237668,https://www.courtlistener.com/opinion/237668/t...,ca6,Court of Appeals for the Sixth Circuit,"[{'opinion_id': 237668, 'opinion_api': None, '...",[237668_010combined.txt],4026202,https://www.courtlistener.com/opinion/4026202/...,ohio,Ohio Supreme Court,,"Mitchell v. Great Eastern Stages, Inc.","Mitchell, Admx., Appellee, v. Great Eastern St...","[1942 Ohio LEXIS 417, 141 A.L.R. 624, 23 Ohio ...",0
4,237668,https://www.courtlistener.com/opinion/237668/t...,ca6,Court of Appeals for the Sixth Circuit,"[{'opinion_id': 237668, 'opinion_api': None, '...",[237668_010combined.txt],4026841,https://www.courtlistener.com/opinion/4026841/...,ohio,Ohio Supreme Court,Bobier,Bobier v. National Casualty Co.,"Bobier, D. B. A. Federal Appliance Service Co....","[1944 Ohio LEXIS 400, 28 Ohio Op. 138, 143 Ohi...",0

In [3]:
eda_cols = ['citing_cluster_id', 'citing_court_name', 'cited_cluster_id', 'cited_court_name', 'cited_target']

for col in eda_cols:
    print("----------")
    print(df[col].nunique())
    display(df[col].value_counts())

----------
1352

citing_cluster_id
9739659    250
1514994    206
443256     195
8935676    193
1639439    189
          ...
560249       1
4865932      1
7346086      1
8614269      1
8162245      1
Name: count, Length: 1352, dtype: int64

----------
171

citing_court_name
Court of Appeals for the Ninth Circuit               3890
District Court, S.D. Florida                         2285
District Court, N.D. California                      2081
Court of Appeals for the Fifth Circuit               2043
District Court, E.D. California                      1804
                                                     ...
Superior Court of Delaware                              5
United States Bankruptcy Court, M.D. Pennsylvania       5
Supreme Court of Delaware                               5
United States Bankruptcy Court, E.D. Arkansas           4
Virginia Beach County Circuit Court                     3
Name: count, Length: 171, dtype: int64

----------
22923

cited_cluster_id
145730     157
145875     137
347621     133
2411022    117
111719     114
          ...
362491       1
417785       1
1479016      1
1798966      1
4236912      1
Name: count, Length: 22923, dtype: int64

----------
338

cited_court_name
Supreme Court of the United States                         10173
Court of Appeals for the Ninth Circuit                      5559
Court of Appeals for the Fifth Circuit                      2463
Court of Appeals for the Eleventh Circuit                   2170
Court of Appeals for the Second Circuit                     2055
                                                           ...
Court of Appeals for the Armed Forces                          1
Pennsylvania Court of Common Pleas, Columbia County            1
Pennsylvania Court of Common Pleas, Philadelphia County        1
U.S. Circuit Court for the District of Indiana                 1
U.S. Navy-Marine Corps Court of Military Review                1
Name: count, Length: 338, dtype: int64

----------
2

cited_target
0    40255
1     1358
Name: count, dtype: int64

# Identify the samples

In [4]:
keep = df[df["cited_target"] == 1]["cited_cluster_id"].to_list()
len(keep)

1358

In [5]:
random.seed(4)
keep_sampled = random.sample(keep, 2)
len(keep_sampled)

2

In [6]:
keep_sampled

[7324900, 415372]

In [7]:
citing_cluster_ids = df[df["cited_cluster_id"].isin(keep_sampled)]["citing_cluster_id"]
len(citing_cluster_ids)

86

In [8]:
sampled_df = df[df["citing_cluster_id"].isin(citing_cluster_ids)]
len(sampled_df)

2432

In [9]:
cited_cluster_ids = list(sampled_df["cited_cluster_id"].unique())
len(cited_cluster_ids)

1520

In [10]:
for col in eda_cols:
    print("----------")
    print(sampled_df[col].nunique())
    display(sampled_df[col].value_counts())

----------
86

citing_cluster_id
9925195     121
9622223      77
9674372      73
9621004      54
429180       52
           ...
8666932       9
9607926       6
529973        6
8666174       3
10599655      1
Name: count, Length: 86, dtype: int64

----------
19

citing_court_name
District Court, N.D. California            914
District Court, S.D. California            330
District Court, E.D. California            207
Court of Appeals for the Second Circuit    191
District Court, D. Oregon                  130
District Court, N.D. Illinois              119
District Court, E.D. New York              101
District Court, W.D. Kentucky               79
District Court, W.D. Washington             71
Court of Appeals for the D.C. Circuit       63
District Court, D. Minnesota                50
District Court, D. Arizona                  50
District Court, D. Massachusetts            33
District Court, N.D. Georgia                31
U S Air Force Court of Military Review      19
Court of Appeals for the Third Circuit      14
District Court, S.D. New York               12
United States Court of Military Appeals     12
Court of Appeals for the Fourth Circuit      6
Name: count, dtype: int64

----------
1520

cited_cluster_id
7324900    69
145730     53
145875     48
1243130    23
7110394    17
           ..
494674      1
8879472     1
8281419     1
7332054     1
1217988     1
Name: count, Length: 1520, dtype: int64

----------
113

cited_court_name
Court of Appeals for the Ninth Circuit             712
Supreme Court of the United States                 336
District Court, N.D. California                    257
California Court of Appeal                         218
Court of Appeals for the Second Circuit            168
                                                  ...
District Court, D. Nevada                            1
Supreme Court of New Jersey                          1
District Court, D. Hawaii                            1
District Court, N.D. Alabama                         1
U.S. Navy-Marine Corps Court of Military Review      1
Name: count, Length: 113, dtype: int64

----------
2

cited_target
0    2346
1      86
Name: count, dtype: int64

# Save the txt files for processing against CLReplica

In [11]:
#with open('data/fed/citing_ids.txt', 'w') as f:
#    for number in citing_cluster_ids:
#        f.write(f"{number}\n")

In [12]:
#with open('data/fed/cited_ids.txt', 'w') as f:
#    for number in cited_cluster_ids:
#        f.write(f"{number}\n")

# Load the citing data extracted from CLReplica

In [13]:
with open('data/fed/citing_opinions.json', 'r') as f:
    results = json.load(f)

In [14]:
citing_metadata = pd.DataFrame.from_dict(results, orient='index')
citing_metadata = citing_metadata.reset_index().rename(columns={'index': 'citing_cluster_id'})
citing_metadata.head()

,citing_cluster_id,citing_url,citing_court_id,citing_court_name,opinion_data,cited_cluster_ids
0,420694,https://www.courtlistener.com/opinion/420694/u...,ca2,Court of Appeals for the Second Circuit,"[{'opinion_id': 420694, 'opinion_api': None, '...","[105249, 301614, 304762, 313088, 318163, 34438..."
1,429180,https://www.courtlistener.com/opinion/429180/u...,cadc,Court of Appeals for the D.C. Circuit,"[{'opinion_id': 429180, 'opinion_api': None, '...","[225685, 332087, 335257, 338658, 340446, 35185..."
2,430620,https://www.courtlistener.com/opinion/430620/u...,ca2,Court of Appeals for the Second Circuit,"[{'opinion_id': 430620, 'opinion_api': None, '...","[358036, 369003, 369008, 395166, 415372, 90251..."
3,436234,https://www.courtlistener.com/opinion/436234/u...,ca2,Court of Appeals for the Second Circuit,"[{'opinion_id': 436234, 'opinion_api': None, '...","[110736, 234593, 337565, 359724, 389257, 41537..."
4,513272,https://www.courtlistener.com/opinion/513272/u...,ca2,Court of Appeals for the Second Circuit,"[{'opinion_id': 513272, 'opinion_api': None, '...","[302623, 323143, 415372, 429277, 479794, 89119..."

In [15]:
citing_metadata.columns

Index(['citing_cluster_id', 'citing_url', 'citing_court_id',
       'citing_court_name', 'opinion_data', 'cited_cluster_ids'],
      dtype='object')

In [16]:
citing_metadata = citing_metadata[['citing_cluster_id', 'citing_url', 'citing_court_name', 'cited_cluster_ids']]
citing_exploded = citing_metadata.explode("cited_cluster_ids", ignore_index=True)

citing_exploded.rename(columns={"cited_cluster_ids": "cited_cluster_id"}, inplace=True)
citing_exploded["cited_cluster_id"] = citing_exploded["cited_cluster_id"].astype(int)
citing_exploded.head()

,citing_cluster_id,citing_url,citing_court_name,cited_cluster_id
0,420694,https://www.courtlistener.com/opinion/420694/u...,Court of Appeals for the Second Circuit,105249
1,420694,https://www.courtlistener.com/opinion/420694/u...,Court of Appeals for the Second Circuit,301614
2,420694,https://www.courtlistener.com/opinion/420694/u...,Court of Appeals for the Second Circuit,304762
3,420694,https://www.courtlistener.com/opinion/420694/u...,Court of Appeals for the Second Circuit,313088
4,420694,https://www.courtlistener.com/opinion/420694/u...,Court of Appeals for the Second Circuit,318163

# Load the cited data extracted from CLReplica

In [31]:
with open('data/fed/cited_opinions.json', 'r') as f:
    results = json.load(f)

In [32]:
cited_metadata = pd.DataFrame.from_dict(results, orient='index')
cited_metadata = cited_metadata.reset_index().rename(columns={'index': 'cited_cluster_id'})
cited_metadata.head()

,cited_cluster_id,cited_url,cited_court_id,cited_court_name,cited_case_name_short,cited_case_name,cited_case_name_full,cited_citations
0,302,https://www.courtlistener.com/opinion/302/chan...,ca9,Court of Appeals for the Ninth Circuit,,Chandler v. State Farm Mutual Automobile Insur...,"Stuart CHANDLER, Individually and on Behalf of...","[2010 WL 938113, 2010 U.S. App. LEXIS 5499, 59..."
1,2490,https://www.courtlistener.com/opinion/2490/spi...,ca2,Court of Appeals for the Second Circuit,Spinelli,Spinelli v. City of New York,"Angela SPINELLI and Olinville Arms, Inc., Plai...","[2009 WL 2413929, 2009 U.S. App. LEXIS 17640, ..."
2,2583,https://www.courtlistener.com/opinion/2583/maj...,ca2,Court of Appeals for the Second Circuit,,"Major League Baseball Properties, Inc. v. Salv...","MAJOR LEAGUE BASEBALL PROPERTIES, INC., Plaint...","[2008 WL 4181298, 2008 U.S. App. LEXIS 19349, ..."
3,107691,https://www.courtlistener.com/opinion/107691/f...,scotus,Supreme Court of the United States,,First Nat. Bank of Ariz. v. Cities Service Co.,First National Bank of Arizona v. Cities Servi...,"[1968 Trade Cas. (CCH) 72,458, 12 Fed. R. Serv..."
4,110916,https://www.courtlistener.com/opinion/110916/c...,scotus,Supreme Court of the United States,Lyons,City of Los Angeles v. Lyons,City of Los Angeles v. Lyons,"[51 U.S.L.W. 4424, 1983 U.S. LEXIS 152, 461 U...."

In [33]:
cited_metadata.columns

Index(['cited_cluster_id', 'cited_url', 'cited_court_id', 'cited_court_name',
       'cited_case_name_short', 'cited_case_name', 'cited_case_name_full',
       'cited_citations'],
      dtype='object')

In [34]:
cited_metadata = cited_metadata[['cited_cluster_id', 'cited_url', 'cited_court_name', 'cited_case_name_short', 'cited_case_name', 'cited_citations']]
cited_metadata["cited_cluster_id"] = cited_metadata["cited_cluster_id"].astype(int)
cited_metadata.head()

,cited_cluster_id,cited_url,cited_court_name,cited_case_name_short,cited_case_name,cited_citations
0,302,https://www.courtlistener.com/opinion/302/chan...,Court of Appeals for the Ninth Circuit,,Chandler v. State Farm Mutual Automobile Insur...,"[2010 WL 938113, 2010 U.S. App. LEXIS 5499, 59..."
1,2490,https://www.courtlistener.com/opinion/2490/spi...,Court of Appeals for the Second Circuit,Spinelli,Spinelli v. City of New York,"[2009 WL 2413929, 2009 U.S. App. LEXIS 17640, ..."
2,2583,https://www.courtlistener.com/opinion/2583/maj...,Court of Appeals for the Second Circuit,,"Major League Baseball Properties, Inc. v. Salv...","[2008 WL 4181298, 2008 U.S. App. LEXIS 19349, ..."
3,107691,https://www.courtlistener.com/opinion/107691/f...,Supreme Court of the United States,,First Nat. Bank of Ariz. v. Cities Service Co.,"[1968 Trade Cas. (CCH) 72,458, 12 Fed. R. Serv..."
4,110916,https://www.courtlistener.com/opinion/110916/c...,Supreme Court of the United States,Lyons,City of Los Angeles v. Lyons,"[51 U.S.L.W. 4424, 1983 U.S. LEXIS 152, 461 U...."

# Create the output df

In [35]:
output = pd.merge(citing_exploded, cited_metadata, how="left", on="cited_cluster_id")
output.head()

,citing_cluster_id,citing_url,citing_court_name,cited_cluster_id,cited_url,cited_court_name,cited_case_name_short,cited_case_name,cited_citations
0,420694,https://www.courtlistener.com/opinion/420694/u...,Court of Appeals for the Second Circuit,105249,https://www.courtlistener.com/opinion/105249/o...,Supreme Court of the United States,Opper,Opper v. United States,"[45 A.L.R. 2d 1308, 99 L. Ed. 101, 1954 U.S. L..."
1,420694,https://www.courtlistener.com/opinion/420694/u...,Court of Appeals for the Second Circuit,301614,https://www.courtlistener.com/opinion/301614/u...,Court of Appeals for the Second Circuit,,United States v. Robert Sarantos and Constanti...,"[1972 U.S. App. LEXIS 11480, 455 F.2d 877]"
2,420694,https://www.courtlistener.com/opinion/420694/u...,Court of Appeals for the Second Circuit,304762,https://www.courtlistener.com/opinion/304762/u...,Court of Appeals for the Second Circuit,,"United States v. Ralph Kelly Taylor, II","[1972 U.S. App. LEXIS 8560, 464 F.2d 240]"
3,420694,https://www.courtlistener.com/opinion/420694/u...,Court of Appeals for the Second Circuit,313088,https://www.courtlistener.com/opinion/313088/u...,Court of Appeals for the Second Circuit,,United States v. Pui Kan Lam,"[1973 U.S. App. LEXIS 8252, 483 F.2d 1202]"
4,420694,https://www.courtlistener.com/opinion/420694/u...,Court of Appeals for the Second Circuit,318163,https://www.courtlistener.com/opinion/318163/u...,Court of Appeals for the Second Circuit,,United States v. John Joseph Frank,[494 F.2d 145]

In [36]:
len(output)

2436

In [42]:
for col in eda_cols[:-1]:
    print("----------")
    print(output[col].nunique())
    display(output[col].value_counts())

----------
86

citing_cluster_id
9925195     121
9622223      77
9674372      73
9621004      54
429180       52
           ...
563802        9
529973        6
9607926       6
8666174       3
10599655      1
Name: count, Length: 86, dtype: int64

----------
19

citing_court_name
District Court, N.D. California            916
District Court, S.D. California            330
District Court, E.D. California            209
Court of Appeals for the Second Circuit    191
District Court, D. Oregon                  130
District Court, N.D. Illinois              119
District Court, E.D. New York              101
District Court, W.D. Kentucky               79
District Court, W.D. Washington             71
Court of Appeals for the D.C. Circuit       63
District Court, D. Minnesota                50
District Court, D. Arizona                  50
District Court, D. Massachusetts            33
District Court, N.D. Georgia                31
U S Air Force Court of Military Review      19
Court of Appeals for the Third Circuit      14
United States Court of Military Appeals     12
District Court, S.D. New York               12
Court of Appeals for the Fourth Circuit      6
Name: count, dtype: int64

----------
1524

cited_cluster_id
7324900    69
145730     53
145875     48
1243130    23
415372     17
           ..
3190265     1
2530589     1
2475734     1
2256245     1
8721527     1
Name: count, Length: 1524, dtype: int64

----------
113

cited_court_name
Court of Appeals for the Ninth Circuit     714
Supreme Court of the United States         336
District Court, N.D. California            257
California Court of Appeal                 220
Court of Appeals for the Second Circuit    168
                                          ...
Wyoming Supreme Court                        1
District Court, E.D. Wisconsin               1
Court of Appeals of Arkansas                 1
Montana Supreme Court                        1
District Court, W.D. Texas                   1
Name: count, Length: 113, dtype: int64

# Save the output df

In [38]:
assert output["cited_cluster_id"].isnull().sum() == 0

In [39]:
assert output["cited_url"].isnull().sum() == 0

In [40]:
output.to_csv("data/fed/federal_citing_cited.csv", index=False)

# Save each citing cluster as a separate csv for expert annotation

In [41]:
for citing_cluster_id in output["citing_cluster_id"].unique():
    annotate = output[output["citing_cluster_id"] == citing_cluster_id].copy()
    annotate["expert"] = None
    annotate["expert_label"] = None
    annotate["expert_notes"] = None
    num_cited = annotate["cited_cluster_id"].nunique()

    expert_folder = f"data/fed/annotations/"
    
    annotate.to_csv(f"{expert_folder}/{num_cited}_{citing_cluster_id}.csv", index=False)