# Clean up output.json

Bill helped me query the database to get all subsequent opinions that cited the cited_cluster_id opinions. This notebook outlines all the steps I undertook to clean the output and filter for only SCOTUS citing opinions.

# Import library

In [1]:
import numpy as np
import pandas as pd

import json

# Load the data & clean

In [5]:
with open("citing/output.json") as f:
    data = json.load(f)

# Flatten into list of rows
rows = []
for outer_id, items in data.items():
    for item in items:
        item["cited_cluster_id"] = int(outer_id)  # Add the outer key as a new column
        rows.append(item)

# Create DataFrame
df = pd.DataFrame(rows)
df.head()

  court       id  cited_cluster_id
0   njd  1481214             84681
1   njd  1441282             84681
2  ohsd  2125838             84681
3  wiwd  1616748             84681
4   mnd  1447888             84681

In [6]:
len(df)

785592

In [7]:
df = df.rename(columns={'court': 'citing_court_id', 'id': 'citing_cluster_id'})
df = df[["cited_cluster_id", "citing_cluster_id", "citing_court_id"]]
df.head()

   cited_cluster_id  citing_cluster_id citing_court_id
0             84681            1481214             njd
1             84681            1441282             njd
2             84681            2125838            ohsd
3             84681            1616748            wiwd
4             84681            1447888             mnd

# Save cleaned output for future use

In [8]:
df.to_csv("citing/clean_output.csv", index=False)

# Filter for SCOTUS & save for future use

In [9]:
scotus = df[df["citing_court_id"] == "scotus"]
len(scotus)

42839

In [10]:
scotus.to_csv("citing/scotus.csv", index=False)